### PR TITLE
Added FF2024

### PR DESCRIPTION
**Pull request by mialondon**

### CODE REVIEW

**Comment by mhucka** [comment]
Thanks for this PR. Unfortunately, the formatting of the addition is not ideal and I'm afraid will not lead to a nice result. I think the following changes are needed. Would you be willing to make these changes? Alternatively, we can merge the PR as-is and then I can edit the result – tell me what you prefer.

Changes:
1. Formatting Markdown in the following way,
  ```
  Something: blah blah blah
  Something else: blah blah blah
  ```
  doesn't lead to separate lines with headings, as might be expected. Instead, the resulting formatted text is run together:
  image
  It looks like the intention was to have separate lines for the items like the date and CFP, and actually, it _is_ possible to get that kind of formatting using a certain Markdown syntax, but I want to suggest in this case it's preferable simply to write the information as prose. So, in other words, make it a single short paragraph, not a database record.

2. I think it would be better not to make entries like this into subsections, but rather as list items. Here I'm following the example of most other "awesome lists" (e.g., [this one](https://github.com/josephmisiti/awesome-machine-learning#javascript) or [this one](https://github.com/vinta/awesome-python#computer-vision)). The required change is simply to not use `###`, and instead make it a bulleted item.

**Comment by mhucka** [comment]
Update: I added past FF events to show the suggested formatting.

**Comment by mialondon** [comment]
Thanks for your comments! I've simplified the entry - how does it look now?

**Comment by mhucka** [comment]
Thanks for working on it. It's still not quite right, but I'll just take the PR and fix up the details.

**Pull request merged**
